# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# Full reference for Standard Spring Boot properties is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
# set -Dspring.profiles.active=<dev|sit|int> as JVM argument to run in desired profile
# If no profile is specified explicitly, application will fall back to default profile, which is "local"

spring:
  application:
    name: spring-boot-jobrunr-mongodb
  devtools:
    add-properties: false
    restart:
      enabled: false
      exclude: logs/*,application.log,*.log,*.log.*
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration

  #------------------------- MongoDB configuration -------------------------
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017}
      database: ${MONGODB_DATABASE:jobrunr}
      auto-index-creation: true
      uuid-representation: standard
  docker:
    compose:
      enabled: false
  messages:
    basename: i18n/messages,i18n/errors,i18n/problems
    cache-duration: PT10S # 10 second, see the ISO 8601 standard
    fallback-to-system-locale: true
    always-use-message-format: false
    use-code-as-default-message: false
  main:
    log-startup-info: true
  task:
    execution:
      thread-name-prefix: spring-task-executor-
      pool:
        core-size: 8
        max-size: 32
        queue-capacity: 10000
        keep-alive: "10s"
  jackson:
    format:
      date-time: iso
    time-zone: IST
    serialization:
      write-dates-with-zone-id: true
      write-dates-as-timestamps: false
    #hateoas:
    #use-hal-as-default-json-media-type: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    problemdetails:
      enabled: false
  threads:
    virtual:
      enabled: true

#------------------------- Swagger configuration -------------------------
springdoc:
  show-actuator: true
  group-configs:
    - group: actuator
      display-name: Actuator
      paths-to-match: /actuator/**
    - group: jobrunr
      display-name: Jobrunr
      paths-to-match: /**/jobrunr/**
  swagger-ui:
    syntaxHighlight:
      activated: true

#------------------------- Jobrunr configuration -------------------------
org:
  jobrunr:
    database:
      skip-create: false
#      table-prefix: "" # allows to set a table prefix (e.g. schema  or schema and tableprefix for all tables. e.g. MYSCHEMA._jobrunr)
      database-name: jobrunr # Override the default database name to use (e.g. use main application database)
#      datasource: "" # allows to specify a DataSource specifically for JobRunr
      type: mongodb # if you have multiple supported storage providers available in your application (e.g. an SQL DataSource and Elasticsearch), it allows to specify which database to choose. Valid values are 'sql', 'mongodb', 'redis-lettuce', 'redis-jedis' and 'elasticsearch'.
    jobs:
      default-number-of-retries: 10 #the default number of retries for a failing job
      retry-back-off-time-seed: 3 #the default time seed for the exponential back-off policy.
#      metrics:
#        enabled: false #Micrometer integration - this was true in v5.
    job-scheduler:
      enabled: true
    background-job-server:
      enabled: true
      thread-type: VirtualThreads # or PlatformThreads, default is VirtualThreads for Java 21 onwards
#      worker-count: "" #this value normally is defined by the amount of CPU's that are available
      poll-interval-in-seconds:  #check for new work every 15 seconds
#      delete-succeeded-jobs-after: 36 #succeeded jobs will go to the deleted state after 36 hours
#      permanently-delete-deleted-jobs-after: 72 #deleted jobs will be deleted permanently after 72 hours
#      metrics:
#        enabled: false #Micrometer integration - this was true in v5.
    dashboard:
      enabled: true
      port: 8000 #the port on which to start the dashboard
#    miscellaneous:
#      allow-anonymous-data-usage: true #this sends the amount of succeeded jobs for marketing purposes

#------------------------- Actuators configuration -------------------------
# If not specified '/actuator' is taken as default. If specified must start with '/'
#management.endpoints.web.base-path=/
# Set it as "*", if you want to expose all actuator endpoints
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,metrics
  metrics:
    tags:
      application: ${spring.application.name}

problem:
  type-url: http://localhost:8080/problems/help.html
  debug-enabled: false
  stacktrace-enabled: false
  cause-chains-enabled: false

server:
  port: 8080
  forward-headers-strategy: framework
#    servlet:
#        context-path: /api
logging:
  level:
    ROOT: info
    '[org.mongodb.driver]': warn
#        '[org.springframework.data.mongodb.core.MongoTemplate]': debug
debug: false

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================
